#pragma once

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_STATUS
#define RGB_MATRIX_STATUS RGB_MATRIX_CUSTOM_empty_effect

#define STATUS_CAPS_COLOR RGB_ORANGE
#define STATUS_LAYER_BASE_COLOR RGB_OFF
#define STATUS_LAYER_GAME_COLOR RGB_WHITE
#define STATUS_LAYER_TEMP_COLOR RGB_RED
